address = "192.168.0.100:3101"
email = "CastelHunterLM@gmail.com"
passowrd = "Chudak1133284848"
host = "smtp.gmail.com"
port = "587"
cost7Day = "199₽"
cost14Day = "299₽"
cost30Day = "399₽"
bankDetails = " - 4890 4947 0618 2144"